languageCode = "en-us"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "http://www.machine-wisdom.com/"
title = "Machine Wisdom"
canonifyurls = true
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Machine Wisdom"
	description = "Machine Learning, Artificial Intelligence, Distributed Systems, Big Data, and all the computer science topics that Younes Abouelnagah and Nada Elasal love."

	# The path must be relative to the static folder
	# favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Machine Wisdom"

		[params.navigation.links]
			portfolio = "Blog"
			aside     = "MISR"
			contact   = "Join the discussion"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Machine Wisdom"
		subtitle   = "To be wise is to find patterns in what has passed to foresee what is yet to become.<br/>To be conscious of such patterns, wise people spend a lot of time contemplating and patiently exercising loops of thought that takes them from one idea to another.<br/>A computer program can exercise billions of loops in a single wall clock second, allowing it to go through an amount of data that would take years for a human to read. This is the edge machines have in terms of wisdom; they are fast and they do not know boredom."
		buttonText = "Read more"


	# About section
	[params.about]
		headline    = "About Machine Learning"
		description = "Machines do not have any edge in terms of cognitive capacity, because it is us humans who have to tell them what to do in each iteration of the loop in order to make any progress. Even the notion of progress has to be simplified in order for machines to comprehend it. Machines, of the Von Neumann sort currently prevalent, can only deal with numbers and they are very clever when it comes to comparing something to zero. Humans devised a mathematical trick to allow machines to comprehend progress, only if the goal is to minimize a particular outcome function. This trick is called convex optimization, and it is at the heart of almost all methods that allow machines to learn something from data."
		button1Text  = "What loop?"
		button1Link = "#page-top"
		button2Text  = "Browse Topics"
		button2Link = "#portfolio"
		


    # Portfolio modals
	[params.portfolio.modal]
        discipline = "Discipline"
        level = "Level"
        category = "Blog posts about"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "MISR: The Machine Intelligence Solutions Repository"
		text="We maintain [a GitHub repository with the Machine Intelligence Solutions](//github.com/machine-wisdom/misr) that we come across. Each solution has code and documentation, and should ideally be a template that can be readily reused. We welcome your contributions!"

		[params.aside.button]
			text = "Contribute"
			link = "//github.com/machine-wisdom/misr"

	# Service section
	[params.services]
		headline = "The people behind Machine Wisdom"

        [[params.services.list]]
            image = "younes.jpg"
            title = "Younes Abouelnagah"
            description = "M.Math in Computer Science<br/>Focus on Natural Language Processing<br/> Passionate about Scalability<br/>"
            # linkedin = "younosnaga"
            linkedinhref = "https://ca.linkedin.com/in/younosnaga"
            emailhref = "mailto:Y O U N E S [at] machine-wisdom.com"

        [[params.services.list]]
			image = "nada.jpg"
			title = "Nada Elasal"
			description = "M.Sc. in Computer Science<br/>Focus on Computer Vision<br/> Passionate about Ed. Tech.<br/>"
			# linkedin = "nadaelasal"
            linkedinhref = "https://ca.linkedin.com/in/nadaelasal"
            emailhref = "mailto:N A D A [at] machine-wisdom.com"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Please [follow us on Twitter](https://twitter.com/machine_wisdom) and join our [Gitter community](https://gitter.im/orgs/machine-wisdom/rooms). If you want to discuss a particular blog post, join its discussion room on Gitter. We also love to talk in the Lobby room about Machine Learning, Artificial Intelligence, Distributed Systems, Big Data, and all those topics we are passionate about."
		gitter = "Machine-wisdom rooms on Gitter"
		gitterhref = "https://gitter.im/orgs/machine-wisdom/rooms"
		twitter = "@machine_wisdom"
		twitterhref = "https://twitter.com/machine_wisdom"
		
