baseurl = "http://www.machine-wisdom.com/"
title = "Machine Wisdom"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Copyright (c) 2016 Younes Abouelnagah"

[author]
    name = "Younes Abouelnagah"

[params]
  DateForm = "2 Jan, 2006"
  Description = "THE BLOG"
  Author = "Younes Abouelnagah"
  email = "Y O U N E S [at] machine-wisdom.com"
  Ganalytics = "XX-00000000-0"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/machinewisdom"
[[params.social]]
    title = "github"
    url = "https://gitter.im/orgs/machine-wisdom/rooms"

[[menu.main]]
  name = "Archives"
  url = "/blog/post/"
  weight = -300

[[menu.main]]
  name = "MISR"
  url = "/#aside"
  weight = -200

[[menu.main]]
  name = "Join the discussion"
  url = "/#contact"
  weight = -100
