baseurl = "http://www.machine-wisdom.com/blog/"
title = "Machine Wisdom"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Copyright (c) 2016 Younes Abouelnagah"

[author]
    name = "Younes Abouelnagah"

[params]
  DateForm = "Mon, Sep 5, 2016"
  Description = "Your site description"
  Author = "Younes Abouelnagah"
  email = "Y O U N E S [at] machine-wisdom.com"
  Ganalytics = "XX-00000000-0"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/machinewisdom"
[[params.social]]
    title = "github"
    url = "https://github.com/machine-wisdom"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
