baseurl = "http://www.machine-wisdom.com/blog/"
title = "Machine Wisdom"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Copyright (c) 2016 Younes Abouelnagah. All rights reserved."

[author]
    name = "Younes Abouelnagah"

[params]
  DateForm = "2 Jan, 2006"
  Description = "THE BLOG"
  Author = "Younes Abouelnagah"
  email = "Y O U N E S [at] machine-wisdom.com"
  Ganalytics = "UA-83687834-1"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/machine_wisdom"
[[params.social]]
    title = "github"
    url = "https://gitter.im/orgs/machine-wisdom/rooms"

[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -300

[[menu.main]]
  name = "Home"
  url = "//www.machine-wisdom.com/"
  weight = -400

[[menu.main]]
  name = "MISR"
  url = "//www.machine-wisdom.com/#aside"
  weight = -200

[[menu.main]]
  name = "Join the discussion"
  url = "//www.machine-wisdom.com/#contact"
  weight = -100
